import express from "express";
import prisma from "../prisma/client.js";
import { getConsensusArchitecture } from "../services/consensusService.js";
import { materializeGitHubRepo } from "../services/githubService.js";

const router = express.Router();

router.post("/generate", async (req, res) => {
  // 1. Auth Guard
  if (!req.isAuthenticated()) {
    return res
      .status(401)
      .json({ message: "Sentinel requires authentication." });
  }

  const { idea, repoName } = req.body;

  try {
    // 2. Multi-Agent Consensus Phase
    // Instead of one AI, this triggers the Architect -> Security -> CTO debate.
    const blueprint = await getConsensusArchitecture(idea);

    // 3. Physical Materialization Phase
    // Materializes the "surviving" architecture directly to GitHub.
    const githubUrl = await materializeGitHubRepo(
      process.env.GITHUB_TOKEN,
      repoName,
      blueprint.files,
    );

    // 4. Persistence Layer (Prisma)
    const project = await prisma.project.create({
      data: {
        name: repoName,
        description: blueprint.summary, // Summary generated by the 'CTO' agent
        githubUrl: githubUrl,
        tasks: {
          create: blueprint.tasks.map((task) => ({
            title: task.title,
            description: task.description,
            bounty: task.bounty,
            difficulty: task.difficulty,
            status: "OPEN", // Initialize as unclaimed
          })),
        },
      },
      include: { tasks: true },
    });

    // 5. Success Response
    res.status(201).json({
      message: "Consensus reached. Repository materialized.",
      project,
    });
  } catch (error) {
    console.error("Sentinel Error:", error.message);
    res.status(500).json({
      error: "The Council failed to reach consensus.",
      details: error.message,
    });
  }
});

export default router;
