import express from "express";
import prisma from "../prisma/client.js";
import { materializeGitHubRepo } from "../services/githubService.js";
import { transformAuditToPrisma } from "../lib/transformAuditResult.js";
import { runAudit } from "../lib/runAudit.js";

const router = express.Router();

const buildFileStructureFromAudit = (auditResult) => {
  const files = {};

  // ── 1. Always-present meta files ─────────────────────────────
  files["README.md"] =
    `# ${auditResult.project_description}\n\n` +
    `**Audit Score:** ${auditResult.final_score}/100  \n` +
    `**Chief Decision:** ${auditResult.final_decision}  \n` +
    `**Refactor Cost:** ${auditResult.refactor_cost_sprints} sprints\n\n` +
    `## Blocking Issues\n` +
    (auditResult.blocking_issues ?? []).map((i) => `- ${i}`).join("\n");

  files["AUDIT.md"] =
    `# Architecture Audit Report\n\n` +
    `**Run ID:** ${auditResult.run_id}  \n` +
    `**Timestamp:** ${auditResult.timestamp}\n\n` +
    `## Chief's Reasoning\n\n${auditResult.chief_reasoning}`;

  // ── 2. One task file per bounty ───────────────────────────────
  (auditResult.bounties ?? []).forEach((bounty) => {
    const slug = bounty.title
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "");
    files[`tasks/${slug}.md`] =
      `# ${bounty.title}\n\n` +
      `**Theme:** ${bounty.theme}  \n` +
      `**Priority:** ${bounty.priority}  \n` +
      `**Complexity:** ${bounty.complexity} sprints  \n` +
      `**Impact Score:** ${bounty.impact_score}/100\n\n` +
      `## Justification\n${bounty.justification}\n\n` +
      `## Files to Create\n` +
      `\`\`\`\n${bounty.suggested_scaffolding}\n\`\`\``;
  });

  // ── 3. Stub every scaffold_files path ────────────────────────
  // These are the actual src/ paths the bounty agent identified.
  // Gives GitHub a real folder/file tree to materialise.
  (auditResult.scaffold_files ?? []).forEach((filePath) => {
    if (!files[filePath]) {
      const ext = filePath.split(".").pop();
      const comment =
        {
          ts: "//",
          js: "//",
          py: "#",
          sql: "--",
          yml: "#",
          yaml: "#",
          sh: "#",
          json: "//",
        }[ext] ?? "//";
      files[filePath] =
        ext === "md"
          ? `<!-- ${filePath} -->\n<!-- Generated by Architecture Agent -->\n`
          : `${comment} ${filePath}\n${comment} Generated by Architecture Agent — implement per bounty task\n`;
    }
  });

  return files;
};

router.post("/generate", async (req, res) => {
  // 1. Auth Guard
  if (!req.isAuthenticated()) {
    return res
      .status(401)
      .json({ message: "Sentinel requires authentication." });
  }

  const { idea, architecture, repoName } = req.body;

  try {
    const auditResult = await runAudit({
      project_description: idea,
      intended_architecture: architecture, // or pass a template string
      codebase_path: null,
      mock_metrics: null,
    });

    // 2. Hard block if chief says REJECT
    if (auditResult.final_decision === "REJECT") {
      return res.status(422).json({
        error: "Chief Arbiter rejected this architecture.",
        blocking_issues: auditResult.blocking_issues,
        score: auditResult.final_score,
      });
    }

    // 3. Materialize to GitHub using bounty scaffolding as file hints
    //    (or pass a predefined file structure — audit doesn't generate files)
    const githubUrl = await materializeGitHubRepo(
      process.env.GITHUB_TOKEN,
      repoName,
      buildFileStructureFromAudit(auditResult), // 👇 see below
    );

    // 4. Transform audit → Prisma shape
    const prismaData = transformAuditToPrisma(auditResult, repoName, githubUrl);

    // 5. Persist
    const project = await prisma.project.create({
      data: prismaData,
      include: { tasks: { include: { subtasks: true } } },
    });

    res.status(201).json({
      message: `Council decision: ${auditResult.final_decision}`,
      project,
      audit_score: auditResult.final_score,
      requires_revision: auditResult.requires_revision,
    });
  } catch (error) {
    console.error("Sentinel Error:", error.message);
    res.status(500).json({
      error: "The Council failed to reach consensus.",
      details: error.message,
    });
  }
});

// GET /projects - Fetch all projects for the logged-in user
router.get("/", async (req, res) => {
  if (!req.isAuthenticated()) {
    return res
      .status(401)
      .json({ message: "Sentinel requires authentication." });
  }
  try {
    const userId = req.user.id;

    const projects = await prisma.project.findMany({
      where: {
        tasks: {
          some: {
            assigneeId: userId,
          },
        },
      },
      include: {
        tasks: {
          orderBy: { dueDate: "asc" }, // Order tasks by urgency
          include: {
            subtasks: {
              orderBy: { priority: "desc" }, // Show High priority subtasks first
            },
            _count: {
              select: { subtasks: true },
            },
          },
        },
      },
      orderBy: { createdAt: "desc" },
    });

    res.json(projects);
  } catch (error) {
    console.error("Fetch Projects Error:", error);
    res.status(500).json({ error: "Could not retrieve projects." });
  }
});

// GET /projects/:id - Fetch a single project with full hierarchy
router.get("/:id", async (req, res) => {
  // 1. Auth Check
  if (!req.isAuthenticated()) {
    return res
      .status(401)
      .json({ message: "Sentinel requires authentication." });
  }

  const { id } = req.params;
  const now = new Date();

  try {
    // 2. Fetch all data in one query
    const project = await prisma.project.findUnique({
      where: { id },
      include: {
        tasks: {
          include: {
            subtasks: {
              include: {
                assignee: { select: { name: true } },
              },
            },
          },
        },
      },
    });

    if (!project) return res.status(404).json({ message: "Project not found" });

    // 3. Compute Sentinel Analytics
    const tasks = project.tasks;
    const totalTasks = tasks.length;

    const completedTasksCount = tasks.filter(
      (t) => t.status === "COMPLETED",
    ).length;

    // Logic for Overdue Tasks
    const overdueTasks = tasks.filter(
      (t) => t.status !== "COMPLETED" && t.dueDate && new Date(t.dueDate) < now,
    );

    // Logic for High Priority Focus
    const criticalFocus = tasks
      .map((task) => ({
        taskId: task.id,
        title: task.title,
        dueDate: task.dueDate,
        highPrioritySubtasks: task.subtasks.filter(
          (s) => s.priority === "HIGH",
        ),
      }))
      .filter((t) => t.highPrioritySubtasks.length > 0);

    // 4. Combined Response Structure
    res.json({
      // Raw Project Data (for rendering the list/tree)
      ...project,

      // Sentinel Insights (for charts and banners)
      analytics: {
        stats: {
          totalTasks,
          completedTasks: completedTasksCount,
          incompleteTasks: totalTasks - completedTasksCount,
          overdueCount: overdueTasks.length,
          completionRate:
            totalTasks > 0 ? (completedTasksCount / totalTasks) * 100 : 0,
        },
        overdueTasks: overdueTasks.map((t) => ({ id: t.id, title: t.title })),
        criticalFocus,
      },
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
